**<span style="font-size:18px; color: LightBlue;">Reading all files and display heads for initial analysis</span>**

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../paediatric-intensive-care-database-1.1.0/SURGERY_VITAL_SIGNS.csv")

df.shape

(1216011, 9)

In [27]:
df = pd.read_csv("../paediatric-intensive-care-database-1.1.0/csv gz files/SURGERY_VITAL_SIGNS.csv")

df.head()

,ROW_ID,SUBJECT_ID,HADM_ID,VISIT_ID,OPER_ID,ITEM_NO,MONITORTIME,ITEMID,VALUE
0,1,4531,104527,1,1,9,2073-09-01 14:50:00,SV1,148
1,2,4531,104527,1,1,10,2073-09-01 14:55:00,SV1,145
2,3,4531,104527,1,1,12,2073-09-01 15:05:00,SV1,150
3,4,4531,104527,1,1,13,2073-09-01 15:05:00,SV1,147
4,5,4322,104884,2,4,15,2097-07-24 15:30:00,SV1,119

In [5]:
df1 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/ADMISSIONS.csv")
df1.shape
df1.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_DEPARTMENT,DISCHARGE_DEPARTMENT,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,ICD10_CODE_CN,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,1,26,100000,2098-11-09 18:30:55,2098-11-14 09:18:00,NaN,General ICU,General ICU,Self Pay,CHN,Not specified,Single,Han ethnic,2098-11-09 18:30:55,2098-11-14 09:18:00,肠粘膜炎,K52.901,0,0
1,2,28,100001,2104-09-03 10:36:47,2104-09-12 14:51:00,2104-09-12 14:51:00,General ICU,General ICU,Self Pay,CHN,Not specified,Single,Han ethnic,2104-09-03 10:36:47,2104-09-12 14:51:00,心肌炎,I51.403,1,0
2,3,29,100002,2062-11-29 20:52:52,2062-12-07 14:27:00,NaN,General ICU,General ICU,Self Pay,CHN,Not specified,Single,Han ethnic,2062-11-29 20:52:52,2062-12-07 14:27:00,溺水,T75.101,0,0
3,4,30,100003,2098-11-21 15:38:47,2098-11-26 01:33:00,2098-11-26 01:33:00,General ICU,General ICU,Discount,CHN,Not specified,Single,Han ethnic,2098-11-21 15:38:47,2098-11-26 01:33:00,NaN,NaN,1,0
4,5,31,100004,2071-11-13 19:43:13,2071-11-15 13:40:00,2071-11-15 13:40:00,General ICU,General ICU,Self Pay,CHN,Not specified,Single,Han ethnic,2071-11-13 19:43:13,2071-11-15 13:40:00,腹泻病,K52.904,1,0

In [6]:
df2 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/CHARTEVENTS.csv")
df2.shape
df2.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,VALUE,VALUENUM,VALUEUOM
0,1,11062,111384,NaN,1008,2077-05-12 06:48:00,2077-05-12 06:48:00,596.0,596.0,ml
1,2,9349,109531,210016.0,1003,2079-01-06 13:53:30,2079-01-06 13:53:30,110.0,110.0,bpm
2,3,11062,111384,211848.0,1004,2077-05-25 21:59:51,2077-05-25 21:59:51,31.0,31.0,bpm
3,4,12441,112881,213285.0,1031,2107-08-18 06:36:47,2107-08-18 06:36:47,30.0,30.0,°C
4,5,9349,109531,210016.0,1001,2079-01-06 13:53:30,2079-01-06 13:53:30,37.4,37.4,°C

In [3]:
df3 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/D_ICD_DIAGNOSES.csv")
df3.shape
df3.head()

,ROW_ID,ICD10_CODE_CN,ICD10_CODE,TITLE_CN,TITLE
0,1,A00.000,A00.0,古典生物型霍乱,"Cholera due to Vibrio cholerae 01, biovar chol..."
1,2,A00.100,A00.1,埃尔托型霍乱,"Cholera due to Vibrio cholerae 01, biovar eltor"
2,3,A00.900,A00.9,霍乱,"Cholera, unspecified"
3,4,A01.000,A01.0,伤寒,Typhoid fever
4,5,A01.001,A01.0,伤寒,Typhoid fever

In [6]:
df15 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/DIAGNOSES_ICD.csv")
df15.head()

   ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD10_CODE_CN
0       1       12575   113742        1       Q43.901
1       2         614   100603        1       G04.916
2       3        1888   101880        1       Q40.001
3       4        8792   108934        1       S02.902
4       5       10368   111492        1       J18.900

In [35]:
df4 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/D_ITEMS.csv")
df4.shape
df4.head()

,ROW_ID,ITEMID,LABEL_CN,LABEL,LINKSTO,CATEGORY,UNITNAME
0,1,1001,体温,Temperature,chartevents,Routine Vital Signs,°C
1,2,1002,脉搏,Pulse,chartevents,NaN,bpm
2,3,1003,心率,Heart Rate,chartevents,Routine Vital Signs,bpm
3,4,1004,呼吸,Respiratory Rate,chartevents,Routine Vital Signs,insp/min
4,5,1006,血氧饱和度,Oxygen saturation,chartevents,Routine Vital Signs,%

In [17]:
df5 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/D_LABITEMS.csv")
df5.shape
df5.head()

,ROW_ID,ITEMID,LABEL_CN,LABEL,FLUID,CATEGORY,LOINC_CODE
0,1,5002,嗜酸性粒细胞,Eosinophils,Blood,Hematology,711-2
1,2,5005,中性粒细胞%(*),Neutrophils %,Blood,Hematology,NaN
2,3,5006,淋巴细胞%(*),"Lymphocytes, Percent",Blood,Hematology,26478-8
3,4,5008,巨噬细胞%(*),Macrophage%,Blood,Chemistry,NaN
4,5,5010,其它细胞%(*),Other cells %,NaN,NaN,NaN

In [18]:
df6 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/EMR_SYMPTOMS.csv")
df6.shape
df6.head()

,ROW_ID,SUBJECT_ID,HADM_ID,EMR_ID,RECORDTIME,SYMPTOM_NAME_CN,SYMPTOM_NAME,SYMPTOM_ATTRIBUTE
0,1,12104,112523,3930272,2100-07-02 13:04:24,咳嗽,cough,+
1,2,12104,112523,3930272,2100-07-02 13:04:24,胃纳可,good appetite,+
2,3,12104,112523,3930272,2100-07-02 13:04:24,神清,good spirit,+
3,4,12104,112523,3930272,2100-07-02 13:04:24,精神软,listless,+
4,5,12104,112523,3930272,2100-07-02 13:04:24,心律齐,regular heart rhythm,+

In [19]:
df7 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/ICUSTAYS.csv")
df7.shape
df7.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,FIRST_CAREUNIT,LAST_CAREUNIT,FIRST_WARDID,LAST_WARDID,INTIME,OUTTIME,LOS
0,1,26,100000,200532,General ICU,General ICU,340,340,2098-11-09 18:30:55,2098-11-14 09:18:00,4.6167
1,2,28,100001,200533,General ICU,General ICU,340,340,2104-09-03 10:36:46,2104-09-12 14:51:00,9.1771
2,3,29,100002,200534,General ICU,General ICU,340,340,2062-11-29 20:52:52,2062-12-07 14:27:00,7.7326
3,4,30,100003,200535,General ICU,General ICU,340,340,2098-11-21 15:38:47,2098-11-26 01:33:00,4.4132
4,5,31,100004,200536,General ICU,General ICU,340,340,2071-11-13 19:43:12,2071-11-15 13:40:00,1.7479

In [20]:
df8 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/INPUTEVENTS.csv")
df8.shape
df8.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,CHARTTIME,AMOUNT,AMOUNTUOM,STORETIME
0,1,2946,103020,203485.0,2092-01-06 07:07:55,355.0,ml,2092-01-06 07:07:55
1,2,2993,103065,203530.0,2098-04-06 06:11:48,336.0,ml,2098-04-06 06:11:48
2,3,2981,103053,203518.0,2102-01-15 06:12:06,72.0,ml,2102-01-15 06:12:06
3,4,2989,103061,203526.0,2097-02-14 06:52:28,1382.0,ml,2097-02-14 06:52:28
4,5,2894,102970,203435.0,2085-05-12 06:12:16,480.0,ml,2085-05-12 06:12:16

In [21]:
df9 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/LABEVENTS.csv")
df9.shape
df9.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ITEMID,CHARTTIME,VALUE,VALUENUM,VALUEUOM,FLAG
0,1,3665,103732,5244,2077-10-25 09:23:38,27.2,27.20,mmHg,l
1,2,3665,103732,5247,2077-10-25 09:23:38,0.86,0.86,NaN,z
2,3,3665,103732,5248,2077-10-25 09:23:38,22.2,22.20,mmol/L,z
3,4,3665,103732,5249,2077-10-25 09:23:38,-0.3,-0.30,mmol/L,z
4,5,3665,103732,5250,2077-10-25 09:23:38,61.4,61.40,%,h

In [22]:
df10 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/MICROBIOLOGYEVENTS.csv")
df10.shape
df10.head()

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTTIME,SPEC_ITEMID,SPEC_TYPE_DESC,ORG_ITEMID,ORG_NAME,AB_ITEMID,AB_NAME,DILUTION_TEXT,DILUTION_COMPARISON,DILUTION_VALUE,INTERPRETATION
0,1,4981,104977,2066-10-09 11:29:00,LIS031294+LIS0204+LIS0320,"血培养含真菌(阳性加药敏),常规药敏定量试验(MIC),耐甲氧西林葡萄球菌检测MRS.AMRS",MIC310,人葡萄球菌,MIC473,莫西沙星,>=8,>=,8.00,R
1,2,4981,104977,2066-10-09 11:29:00,LIS031294+LIS0204+LIS0320,"血培养含真菌(阳性加药敏),常规药敏定量试验(MIC),耐甲氧西林葡萄球菌检测MRS.AMRS",MIC310,人葡萄球菌,MIC470,克林霉素,<=0.25,<=,0.25,R
2,3,4981,104977,2066-10-09 11:29:00,LIS031294+LIS0204+LIS0320,"血培养含真菌(阳性加药敏),常规药敏定量试验(MIC),耐甲氧西林葡萄球菌检测MRS.AMRS",MIC310,人葡萄球菌,MIC1015,喹奴普汀/达福普汀,<=0.25,<=,0.25,S
3,4,4981,104977,2066-10-09 11:29:00,LIS031294+LIS0204+LIS0320,"血培养含真菌(阳性加药敏),常规药敏定量试验(MIC),耐甲氧西林葡萄球菌检测MRS.AMRS",MIC310,人葡萄球菌,MIC1215,替加环素,<=0.12,<=,0.12,S
4,5,4981,104977,2066-10-09 11:29:00,LIS031294+LIS0204+LIS0320,"血培养含真菌(阳性加药敏),常规药敏定量试验(MIC),耐甲氧西林葡萄球菌检测MRS.AMRS",MIC1703,革兰阳性球菌（G+C）,,,NaN,NaN,NaN,

In [23]:
df11 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/OR_EXAM_REPORTS.csv")
df11.shape
df11.head()

,ROW_ID,SUBJECT_ID,HADM_ID,EXAMTIME,REPORTTIME,EXAM_ITEM_TYPE_NAME,EXAM_ITEM_NAME,EXAM_PART_NAME
0,1,1491,101788,2075-04-08 07:44:45,2075-04-08 07:45:08,CR,DR,Chest
1,2,7525,107581,2091-09-08 10:25:15,2091-09-08 14:37:55,CR,X-rays,Chest
2,3,8811,108952,2115-11-13 10:57:33,2115-11-13 10:56:41,CR,X-rays,Chest
3,4,8423,108545,2106-12-17 19:50:59,2106-12-17 22:11:52,CR,X-rays,Chest
4,5,8232,108356,NaN,2114-09-27 15:39:25,GM,Routine Pathologic Examination,NaN

In [24]:
df12 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/OUTPUTEVENTS.csv")
df12.shape
df12.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,CHARTTIME,ITEMID,VALUE,VALUEUOM,STORETIME
0,1,8800,108941,NaN,2080-11-15 21:11:00,1034,39.0,ml,2080-11-15 21:11:00
1,2,8800,108941,NaN,2080-11-17 18:00:00,1034,6.0,ml,2080-11-17 18:00:00
2,3,8800,108941,NaN,2080-11-22 02:44:00,1034,30.0,ml,2080-11-22 02:44:00
3,4,8800,108941,NaN,2080-11-21 15:05:00,1034,36.0,ml,2080-11-21 15:05:00
4,5,8800,108941,NaN,2080-11-21 06:11:00,1034,10.0,ml,2080-11-21 06:11:00

In [25]:
df13 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/PATIENTS.csv")
df13.shape
df13.head()

,ROW_ID,SUBJECT_ID,GENDER,DOB,DOD,EXPIRE_FLAG
0,1,2,M,2068-11-30 00:00:00,2081-09-28 10:06:00,1
1,2,9,M,2104-03-09 00:00:00,NaN,0
2,3,56,F,2110-01-08 13:40:00,NaN,0
3,4,79,F,2094-08-25 00:00:00,NaN,0
4,5,96,M,2050-12-17 00:00:00,NaN,0

In [29]:
df14 = pd.read_csv("../paediatric-intensive-care-database-1.1.0/PRESCRIPTIONS.csv")
df14.shape
df14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1256591 entries, 0 to 1256590
Data columns (total 13 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ROW_ID             1256591 non-null  int64
 1   SUBJECT_ID         1256591 non-null  int64
 2   HADM_ID            1256591 non-null  int64
 3   ICUSTAY_ID         857884 non-null   float64
 4   STARTDATE          1256589 non-null  object
 5   ENDDATE            275511 non-null   object
 6   DRUG_NAME          1256591 non-null  object
 7   DRUG_NAME_EN       1256591 non-null  object
 8   PROD_STRENGTH      1233998 non-null  object
 9   DRUG_NAME_GENERIC  76888 non-null    object
 10  DOSE_VAL_RX        1256591 non-null  float64
 11  DOSE_UNIT_RX       1245243 non-null  object
 12  DRUG_FORM          1256588 non-null  object
dtypes: float64(2), int64(3), object(8)
memory usage: 124.6+ MB